# -*- coding: utf-8 -*-
"""Make Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pk03_ztpwcEGiKSFTBqTMUOwLJjePzx0
"""

import json

def make_matrix (all_diffs, stanza_type_dict):
  # Construct the matrix
  output_matrix = []

  for (date, date_diffs) in all_diffs.items():
    temp_list = [0] * len(stanza_type_dict.keys())

    for (device_name, device_diffs) in date_diffs.items():
      for (element_name, small_value) in device_diffs.items():
        # Capture multiple changes at same location
        if (len(small_value) < 3): # Not general enough, change later
          for i in range(len(small_value)):
            if (small_value[i][0] in stanza_type_dict):
              temp_list[stanza_type_dict[small_value[i][0]]] = 1
        else:
          if (small_value[0] in stanza_type_dict):
            temp_list[stanza_type_dict[small_value[0]]] = 1

    output_matrix.append(temp_list)

  return output_matrix

def main (dates, stanza_type_dict):
  all_diffs = {}
  for date in dates:
    with open(date, 'r') as infile:
      date_diffs = json.load(infile)
    all_diffs[date.split('.')[0]] = date_diffs
  
  # Record differences in matrix
  matrix = make_matrix(all_diffs, stanza_type_dict)
  print(matrix)

dates = ['2021-08-09vs2021-09-09.json',
           '2021-09-09vs2021-10-09.json',
           '2021-10-09vs2021-11-09.json',
           '2021-11-09vs2021-12-09.json']
  
# Hard code stanza type dictionary for now
stanza_type_dict = {"ACL": 0,
                    "Interface": 1,
                    "PKI_TA_Profile": 2,
                    "Port": 3,
                    "SNMP_Trap": 4,
                    "System": 5,
                    "User": 6,
                    "User_Group": 7,
                    "VLAN": 8,
                    "VRF": 9}

if __name__ == "__main__":
  main(dates, stanza_type_dict)